deepin-community/Repository-Manager

- .github/workflows/auto-create-repo.yml
- OWNERS
- README.md
- repos.yml
> 添加文档和review人员列表

- OWNERS
> chore: add xzl01 to OWNERS

- repos.yml
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈
add rust-unicode-xid
> add 'rust-unicode-xid'

- repos.yml
[feat: Implementations of string similarity metrics - Rust source code](https://github.com/deepin-community/Repository-Manager/pull/61/commits/ce745c6657079382e2623ee7731da3d38556ce69) 
Includes Hamming, Levenshtein, OSA, Damerau-Levenshtein, Jaro, Jaro-Winkler,
and SÃ¸rensen-Dice.
.
This package contains the source for the Rust strsim crate, packaged by
debcargo for use with cargo and dh-cargo.
Log: Implementations of string similarity metrics - Rust source code
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/56
Task: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/5
Influence: Implementations of string similarity metrics - Rust source code
> add rust-strsim

- repos.yml
Discus aims to make df prettier, with features such as color, graphs, and smart formatting of numbers
Log: add discus
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/62
Task: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/5
Influence: source files of discus would be added
> feat: add discus

- repos.yml
Fast float parsing conversion routines.
Log: add rust-minimal-lexical
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/71
> feat: add rust-minimal-lexical

- repos.yml
It provides a struct similar to Cell that can be lazily filled.
Log: add rust-lazycell
Issue:deepin-community/sig-deepin-sysdev-team#77
> feat: add rust-lazycell

- repos.yml
Low level interface to CloudABI
Log: add rust-cloudabi
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/80
> feat: add rust-cloudabi

- repos.yml
Synaptic is a graphical package management tool based on GTK+ and APT.
Log: add synaptic
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/78
> feat: add synaptic

- repos.yml
These are various tools for manipulating JET / MS Access database (MDB) files
Log: add mdbtools
Issues: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/117
> feat: add mdbtools

- repos.yml
a pop-style font
Log: add fonts-rocknroll
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/157
> feat: add fonts-rocknroll

- repos.yml
rust-dtoa: the source for the Rust dtoa crate
rust-libm: the source for the Rust libm crate
rust-rustc-version: the source for the Rust rustc_version crate
rust-ryu: the source for the Rust ryu crate
rust-semver: the source for the Rust semver crate
rust-stackvector: the source for the Rust stackvector crate
rust-static-assertions: the source for the Rust static_assertions crate
rust-unreachable: the source for the Rust unreachable crate
rust-void: the source for the Rust void crate
Log: add rust-cexpr, rust-lexical-core
Issue:
deepin-community/sig-deepin-sysdev-team#131 (rust-dtoa),
deepin-community/sig-deepin-sysdev-team#132 (rust-libm),
deepin-community/sig-deepin-sysdev-team#133 (rust-rustc-version),
deepin-community/sig-deepin-sysdev-team#92 (rust-ryu), …
> feat: add rust-dtoa, rust-libm, rust-rustc-version, rust-ryu, rust-semver, rust-stackvector, rust-static-assertions, rust-unreachable, rust-void

- repos.yml
It is a library for parsing, compiling, and executing regular expressions.
Log: add rust-regex-syntax
Issue:deepin-community/sig-deepin-sysdev-team#101
> add rust-regex-syntax

- repos.yml
pysimplesoap: simple and lightweight SOAP Library (Python 3)
Log: add pysimplesoap
Issue:deepin-community/sig-deepin-sysdev-team#199
> feat: add pysimplesoap

- repos.yml
rust-smawk, functions for finding row-minima in a totally monotone matrix. rust-fnv, fowler–Noll–Vo hash function.
rust-getrandom, retrieve random data from system source. rust-hex, encoding and decoding data into/from hexadecimal representation. rust-seahash, blazingly fast, portable hash function with proven statistical guarantees. rust-serde-json, JSON serialization file format.
Log: rust-smawk, rust-fnv, rust-getrandom, rust-hex, rust-seahash, rust-serde-json would be added.
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/105
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/140
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/142
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/143 …
> feat: add rust-smawk, rust-fnv, rust-getrandom, rust-hex, rust-seahash, rust-serde-json

- repos.yml
Free and Open Music Notation Editor
Log: add denemo
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/206
> feat: add denemo

- repos.yml
Development files for the KDE games library.
Log: add libkdegames
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/207
> feat: add libkdegames

- repos.yml
program for typesetting sheet music
Log: add lilypond
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/213
> feat: add lilypond

- repos.yml
fonts-beteckna, geometric Futura-like sans-serif TrueType font rust-humantime, Parser and formatter for std::time::{Duration, SystemTime} 
Log: add fonts-beteckna, rust-humantime
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/224 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/32
> feat: add fonts-beteckna, rust-humantime

- repos.yml
Log: delete rust-humantime
Influence: rust-humantime will be deleted
> feat: delete rust-humantime

- repos.yml
Hack is designed to be a workhorse typeface for source code.
Log: add fonts-hack
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/46
Task: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/4
Influence: fonts hack would be added
> feat: add fonts-hack

- repos.yml
It is a C++ library that supports a few operations on boolean expression binary trees.
Log: add boolstuff
Issue:deepin-community/sig-deepin-sysdev-team#192
> feat: add boolstuff

- repos.yml
erfs: An easy-to-use, easy-to-setup, hassle-free secure file system with the encrypted data being stored on a remote cloud server without having to trust the server.
gamgi: GAMGI is a graphical interface tool used to establish, view, and analyze atomic structures.
gliese: stellar data set from the Third Catalogue of Nearby Stars.
netdata: real-time performance monitoring (metapackage).
socket: The socket program is a simple tool for socket based connections. It can be used to create simple daemons (in both standalone and inetd mode), to connect to other daemons or to redirect ports.
log: add erfs, gamgi, gliese, netdata, socket
issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/226 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/227 …
> feat: add erfs, gamgi, gliese, netdata, socket

- repos.yml
rust-serde-json, JSON serialization file format.
Log: rust-serde-json would be added.
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/148
> feat: add rust-serde-json

- repos.yml
rust-regex, Regular expressions for Rust.
rust-fxhash, RFast, non-secure, hashing algorithm. rust-byteorder, Reading/writing numbers in big-endian and little-endian.
Log: rust-regex, rust-fxhash, rust-byteorder would be added.
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/108
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/141
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/244
> feat: add rust-regex, rust-fxhash, rust-byteorder

- repos.yml
atop, Monitor for system resources and process activity
meld, graphical tool to diff and merge files
xdelta3, Diff utility which works with binary files
pixz, parallel, indexing XZ compressor/decompressor
cppcheck, tool for static C/C++ code analysis (CLI)
exif, command-line utility to show EXIF information in JPEG files
Log: add atop,meld,xdelta3,pixz,cppcheck,exif
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/241
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/242
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/249
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/251
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/252
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/254
> feat: add atop,meld,xdelta3,pixz,cppcheck,exif

- repos.yml
Failed to create repositories above.
Log: delete libspnav, log4cplus, imath
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/245 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/256 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/263
> feat: delete libspnav, log4cplus, imath

- repos.yml
wrk: HTTP benchmarking tool
motif: Motif - development files
xball: Simulate bouncing balls in a window
Log: add wrk, libmotif-dev, xball
Issue:
deepin-community/sig-deepin-sysdev-team#264
deepin-community/sig-deepin-sysdev-team#273
deepin-community/sig-deepin-sysdev-team#274
> feat: add wrk,motif, xball

- repos.yml
feat: add fonts-arundina,fonts-mlym,fonts-uralic,fonts-arphic-ukai,fonts-fork-awesome,fonts-material-design-icons-iconfont
Custom icon webfonts from the comfort of the command line
Thai DejaVu-compatible fonts
Meta package to install all Malayalam fonts
Truetype fonts for Cyrillic-based Uralic languages
"AR PL UKai" Chinese Unicode TrueType font collection Kaiti style
Fork of the iconic font and CSS toolkit
Material Design Icons DX
Log: add fonts-arundina,fonts-mlym,fonts-uralic,fonts-arphic-ukai,fonts-material-design-icons-iconfont 
Issues:https://github.com/deepin-community/sig-deepin-sysdev-team/issues/266 
Issues:https://github.com/deepin-community/sig-deepin-sysdev-team/issues/267 
Issues:https://github.com/deepin-community/sig-deepin-sysdev-team/issues/268 …
> feat: add fontcustom,fonts-arundina,fonts-mlym,fonts-uralic,fonts-arphic-ukai,fonts-fork-awesome,fonts-material-design-icons-iconfont

- repos.yml
It is a process for converting text (strings) into data structures.
Log: add parser
Issue:deepin-community/sig-deepin-sysdev-team#282
deepin-community/sig-deepin-sysdev-team#283
deepin-community/sig-deepin-sysdev-team#284
deepin-community/sig-deepin-sysdev-team#285
deepin-community/sig-deepin-sysdev-team#286
> feat: add parser

- repos.yml
DebianDoc SGML DTD and formatting tools
Log: add debiandoc-sgml
Issues: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/308
> feat: add debiandoc-sgml

- repos.yml
> feat: add libnetfilter-acct

- repos.yml
> feat: add wlroots-git

- repos.yml
Resource-acquisition-is-initialization scope guard - Rust source code
Log: rust-scopeguard would be added.
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/302
> feat: add golang-github-go-macaron-toolbox

- repos.yml
GNOME library to manage keyboard configuration
Log: add libgnomekbd
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/348
> feat: add libgnomekbd

- repos.yml
jq: lightweight and flexible command-line JSON processor.
mc: Midnight Commander - a powerful file manager.
Log: add jq, mc
Issue:
deepin-community/sig-deepin-sysdev-team#349
deepin-community/sig-deepin-sysdev-team/issues/355
> feat: add jq, mc

- repos.yml
Fix yaml format of file `repo.yml`
> feat: fix yaml format

- repos.yml
Sort repos.yml using [format-repo.py](https://gist.github.com/YukariChiba/6fe00de84b7a8529be4d4c148e0b850b). (Avoid rebase for PRs)
(formatted version of HEAD 22378b7ec501d3ffc3057f01eee356a96828d915)
TODO: Add checker in workflow
> Sort repos.yml

- repos.yml
netaddr is a Python library for the manipulation of various common network address notations and representations. progressbar is a text progress bar library for Python (Python 3) 
mailer is a Python module that simplifies sending email (Python 3) 
characteristic is Python package with class decorators that ease the chores of implementing the most common attribute-related object protocols. 
meld3 is an HTML/XML templating system for Python 2.3+
Log: add python-netaddr, python-progressbar, python-mailer, python-characteristic, python-meld3 
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/377 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/378 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/383 …
> feat: add python-netaddr, python-progressbar, python-mailer, python-characteristic, python-meld3

- repos.yml
Add package `imagemagick`, required by `zbar` and many other packages
> feat: add package imagemagick

- repos.yml
Tools for the Observational Data Processing (ODB)
Log: add odc to fix magicsplusplus
Issues: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/387
> feat: add odc to fix magicsplusplus

- repos.yml
Recursively walk a directory - Rust source code
Log: rust-walkdirrust-walkdir would be added.
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/382
feat: rust-same-file
Simple crate for determining whether two file paths point to the same file
Log: rust-same-file would be added.
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/389
> feat: rust-walkdir 

- repos.yml
KVTML files for KDE-Edu programs
Log: add kdeedu-data
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/393
> feat: add kdeedu-data

- repos.yml
Fix a typo in https://github.com/deepin-community/Repository-Manager/pull/176
> fix: deepin-sysdev-team is group

- repos.yml
bb: ASCII-art demo based on AAlib
flake: Alternative encoder for the Free Lossless Audio Codec
missidentify: find win32 applications
Log: add bb, flake, missidentify
Issue:
deepin-community/sig-deepin-sysdev-team#364
deepin-community/sig-deepin-sysdev-team#365
deepin-community/sig-deepin-sysdev-team#367
> feat: add bb, flake, missidentify

- repos.yml
cohomcalg:It is a software package for computing sheaf cohomologies of line bundles on toric varieties.
coinor-csdp:It is a software package for solving semidefinite programming problems.
coinor-bonmin:It can solve general MINLP (Mixed Integer NonLinear Programming) problems.
coinor-dylp:It is a software package for solving constrained linear mathematical optimization problems.
Log: add aohomcalg,coinor-csdp,coinor-bonmin,coinor-dylp
Issue:deepin-community/sig-deepin-sysdev-team#403
deepin-community/sig-deepin-sysdev-team#404
deepin-community/sig-deepin-sysdev-team#407
deepin-community/sig-deepin-sysdev-team#408
deepin-community/sig-deepin-sysdev-team#409
deepin-community/sig-deepin-sysdev-team#410
deepin-community/sig-deepin-sysdev-team#411
deepin-community/sig-deepin-sysdev-team#412 …
> feat: add cohomcalg,coinor-csdp,coinor-bonmin,coinor-dylp

- repos.yml
Python ASGI web microframework with the same API as Flask
Log: add quart
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/420
> feat: add quart

- repos.yml
> feat: add dependencies for wlroots-git

- repos.yml
Issue with workflow, retry it.
Reverts deepin-community/Repository-Manager#194
> Revert "feat: add dependencies for nexttrace"

- repos.yml
Issue with workflow, retry it.
Reverts deepin-community/Repository-Manager#186
> Revert "fix: change repo name, format yaml file"

- .github/workflows/auto-create-repo.yml
Same as https://github.com/deepin-community/.github/pull/72
> fix by config nodejs version to 18
>
> Issue: https://github.com/octokit/auth-app.js/issues/499
> fix(CI): github scripts get token error

- repos.yml
Managing temporary files and directories - Rust source code
Log: rust-tempfile would be added.
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/401
feat: rust-tempfile
Managing temporary files and directories - Rust source code
Log: rust-tempfile would be added.
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/401
feat: rust-fastrand
Simple and fast random number generator - Rust source code
Log: rust-fastrand would be added.
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/477
feat: rust-redox-syscall
Access raw Redox system calls - Rust source code
Log: rust-redox-syscall would be added.
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/478
feat: rust-bitflags-1
Macro to generate structures …
> feat: rust-tempfile

- repos.yml
Workflow has been fixed.
Reverts deepin-community/Repository-Manager#200
> Revert "Revert "fix: change repo name, format yaml file""

- repos.yml
add `libcamera`, `libfreeaptx`, `liblc3`
> feat: add dependencies for pipewire

- repos.yml
Add package `mtr`: Full screen ncurses and X11 traceroute tool
> feat: add package mtr

- repos.yml
add `wireplumber`: modular session / policy manager for PipeWire`
> Add package wireplumber

- repos.yml
> feat: dh-nss

- repos.yml
> feat: add package cataclysm-dda

- repos.yml
Execute commands in a chroot environment
Ref: https://github.com/orgs/linuxdeepin/discussions/3566
> feat: schroot

- repos.yml
format repos.yml using [format-repo.py](https://gist.github.com/chenchongbiao/aeadf84e29d68656f3c74b5d9007f1af)
Modify from [format-repo.py](https://gist.github.com/YukariChiba/6fe00de84b7a8529be4d4c148e0b850b).
> fix: format yml file

- repos.yml
Extract page mode and named destinations as PDFmark from PDF
> chore: add extractpdfmark repo

- repos.yml
> feat: add waypipe

- repos.yml
module for parsing the data from a Debian Packages.gz
这是 multistrap 的依赖，multistrap 是制作根文件系统的工具，类似 debootstrap
> chore: add libparse-debian-packages-perl repo

- repos.yml
Provides POSIX tarchive management for Ruby
> chore: add ruby-minitar repo

- repos.yml
dde-control-center depends on these packages
> feat: add openvpn and strongswan

- repos.yml
> chore: app repo

- repos.yml
> chore: add fastfetch

- repos.yml
> fix: revert since repo is not created

- repos.yml
https://github.com/deepin-community/Repository-Manager/pull/230
> feat: add package gopacket

- repos.yml
> chore: Add sensors-applet

- repos.yml
> feat: add kruler

- repos.yml
> feat: add kexec-tools

- repos.yml
> feat: add kdump

- repos.yml
The source package of strongswan-nm is strongswan
Log:
> chore: delete strongswan-nm

- repos.yml
* add package highway rust-rav1e libjxl-testdata for kde-relate upgrade.
log: add packages.
> feat: add 3 new packages.

- repos-exit-records.yml
used for deepin repository and package exit workflow
log:
> feat: Add repository exit records file

- repos.yml
> feat: add cpufrequtils

- repos.yml
> feat: add ocaml-graphics

- repos.yml
> feat: add ocaml-odoc dependencies

- repos.yml
> feat: add bear

- repos.yml
add `iperf3`:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/510
> feat: add iperf3

- repos.yml
https://codeberg.org/dnkl/foot
> feat: add foot

- repos.yml
> feat: add pkgs fcft and tllist

- repos.yml
dependency of `haskell-devscripts-minimal`
> feat: add html-xml-utils

- repos.yml
> chore: add libopenaptx

- repos.yml
dependency of https://build.deepin.com/project/show/home:yukarichiba:python
> feat: add python packages (dependencies for upgrade)

- repos.yml
Remote Desktop Protocol (RDP) server
Log: add xrdp
> chore: add xrdp

- repos.yml
Remote Desktop Protocol (RDP) modules for X.org
Log: add repo
> feat: add xorgxrdp

- repos.yml
- Add `libre-engine-re2-perl`
- Add `libmoox-struct-perl`
> Add dependencies for licensecheck

- repos.yml
https://wayfire.org
Wayfire is a wayland compositor based on [wlroots](https://github.com/swaywm/wlroots). It aims to create a customizable, extendable and lightweight environment without sacrificing its appearance.
> feat: add doctest, wf-config and wayfire

- repos.yml
> feat: add package flit-scm

- repos.yml
> chore: add repos

- repos.yml
> chore: add dh-vim-addon

- repos.yml
> feat: add wcag-contrast-ratio

- repos.yml
> feat: add cmatrix

- repos.yml
Build dependency of fonttools.
> feat: sphinx-inline-tabs

- repos.yml
add printer-driver-c2050
Log: update repos
> chore: update repos

- repos.yml
+eckit=1.24.4-1
+ismrmrd=1.8.0-2
+libstrophe=0.12.3-1
+loudmouth=1.5.4-1
+mongo-c-driver=1.23.1-1
> Add libraries

- repos.yml
> chore: add kodi dependencies

- repos.yml
ROCm System Management Interface (ROCm SMI). Build-Dependency of
slurm-wlm.
> feat: add rocm-smi-lib

- repos.yml
Build dependency of rocm-smi-lib
> feat: dot2tex

- repos.yml
- add `3270font`
- add `cool-retro-term`
- add `fonts-homecomputer`
- add `qmltermwidget`
> feat: add dependencies for cataclysm-dda

- repos.yml
add `vfit`, dependency for `fonts-homecomputer`
> feat: add vfit

- repos.yml
> chroe: add deps

- repos.yml
> chore: add dependencies

- repos.yml
libgssglue repo  creation unsuccessful
Log: delete libgssglue
> chore: delete libgssglue

- repos.yml
header files and docs for libgssglue
Log: update repo
> chore: add libgssglue

- repos.yml
simplistic port-like solution for developers
Log: update repo
> chore: add ruby-mini-portile2

- repos.yml
> feat: add boost 1.81

- repos.yml
dependencies of `openttd`:
- `grfcodec`
- `openttd-open{gfx,msx,sfx}`
> feat: add denepdencies for openttd

- repos.yml
> feat: add dependencies for prismlauncher

- repos.yml
> feat: add libmypaint

- repos.yml
dependency of ``openttd-opensfx`
> feat: add catcodec

- repos.yml
dependency of `openttd-opengfx`
> feat: add nml

- repos.yml
> feat: add dependencies of yuzu

- repos.yml
> chore: add some dependencies of ibus

- repos.yml
> feat: add dependencies for qemu

- repos.yml
> feat: add timeshift

- repos.yml
> feat: add libmongocrypt and dependencies

- repos.yml
> add natsort

- repos.yml
patch maintenance system for Debian source packages
Log: add repo
> chore: add dpatch

- repos.yml
> feat: add llvm-tool-chain 15,16,17

- repos.yml
readline5,mariadb,golang-github-satori-go.uuid,golang-go-xdg
Log: add repo
> chore: add repo

- repos.yml
> chore: add distcc

- repos.yml
> feat: add dependencies of hyprland

- repos.yml
> chore: add spirv-llvm-translator

- repos.yml
> feat: add dependencies of neovim

- repos.yml
> fix: fix spell error

- repos.yml
dependency of `ipxe`, which is dependency of `qemu`
> feat: add package dpkg-source-gitarchive

- repos.yml
> feat: add dependencies of virtualbox(stage 1)

- repos.yml
> feat: add dependencies of virtualbox(stage 2)

- repos.yml
> feat: add fonts-nanum

- repos.yml
- qwlroots
- waylib
- treeland
- dofi
> feat: add vioken packages

- repos.yml
> chore: add qcoro

- repos.yml
> chore: add synergy

- repos.yml
> chore: add isa-support

- repos.yml
Haskell library for uniform type generic traversals
Log: add repo
> chore: add haskell-uniplate

- repos.yml
> chore: add speexdesp

- repos.yml
rename speexdsp
Log: fix repo name
> fix: fix repo name

- repos.yml
run external processes, with strong typing of streams
opencv 依赖
Log: add repo
> feat: add haskell-typed-process

- repos.yml
batteries-included conduit: adapters for common libraries
opencv依赖
Log: add repo
> feat: add haskell-conduit-extra

- repos.yml
basic types for representing XML
opencv依赖
Log: add repo
> feat: add haskell-xml-types

- repos.yml
HTTP client package with conduit interface and HTTPS support
opencv依赖
Log: add repo
> feat: add haskell-xml-conduit

- repos.yml
time a computation
opencv 依赖
Log: add repo
> feat: add haskell-timeit

- repos.yml
> chore: add sphinx-press-theme

- repos.yml
Generates citations and bibliography from CSL styles
opencv 依赖
Log: add repo
> feat; add haskell-citeproc

- repos.yml
> feat: add xdg-terminal-exec

- repos.yml
> chore: Add RyzenAdj

- repos.yml
Pure Haskell commonmark parser
Log: add repo
> chore: add haskell-commonmark

- repos.yml
Pure Haskell commonmark parser extensions
Log: add repo
> feat: add haskell-commonmark-extensions

- repos.yml
Bridge between commonmark and pandoc AST
Log: add repo
> feat: add haskell-commonmark-pandoc

- repos.yml
> chore: add python-glad

- repos.yml
Lua bindings for Haskell; documentation
Log: add repo
> feat: add haskell-lua

- repos.yml
Arbitrary instances for Lua types; profiling libraries
Log: add repo
> feat: add libghc-lua-arbitrary-prof

- repos.yml
Lua bindings for Haskell; documentation
Log: add repo
> feat: add haskell-hslua-core

- repos.yml
> feat: add onevpl

- repos.yml
> feat: add docopt.cpp

- repos.yml
Type classes for HsLua
Log: add repo
> feat: add haskell-hslua-classes

- repos.yml
Object orientation tools for HsLua
Log: add repo
> feat: add haskell-hslua-objectorientation

- repos.yml
Utilities to build Lua modules
Log: add repo
> feat: add haskell-hslua-packaging

- repos.yml
libelfin-dev,libargtable2-dev
deepin-unioncode 依赖
Log: add repo
> feat: add repo

- repos.yml
Use pandoc types in Lua; documentation
Log: add repo
> feat: add haskell-pandoc-lua-marshal

- repos.yml
> feat: add node-sinclair-typebox

- repos.yml
> chore: add glances

- repos.yml
LPeg – Parsing Expression Grammars For Lua; documentation
Log: add repo
> feat: add haskell-lpeg

- repos.yml
Lua module to work with file paths.; documentation
Log: add repo
> chore: add haskell-hslua-module-path

- repos.yml
> feat: add golang-github-tsosunchia-powclient

- repos.yml
memory-efficient representation of Unicode text strings; documentation
Log: add repo
> chore: add haskell-text-short

- repos.yml
Strict variants of standard Haskell datatypes; documentation
Log: add repo
> feat: add haskell-strict

- repos.yml
fixpoint data types; documentation
Log: add repo
> chore: add haskell-data-fix

- repos.yml
> feat: add haskell-onetuple

- repos.yml
> chore: add some nodes package

- repos.yml
Extra instances for indexed traversables in Haskell
Log: add repo
> feat: add haskell-indexed-traversable-instances

- repos.yml
filterable traversable for Haskell
Log: add repo
> feat: add haskell-witherable

- repos.yml
Backward (and forward) compatible Quote and Code types
Log: add repo
> feat: add haskell-th-compat

- repos.yml
> feat: Add ryzen-smu

- repos.yml
> feat: add tlp

- repos.yml
> feat: add stdeb

- repos.yml
> chore: add filezilla

- repos.yml
> feat: add ikwiki

- repos.yml
> feat: add libhtml-scrubber-perl

- repos.yml
> chore: add VNC

- repos.yml
> chore: add graphene

- repos.yml
> chore: add krfb

- repos.yml
> chore: add kpipewire

- repos.yml
> add papyrus

- repos.yml
> add socketplusplus eigen3

- repos.yml
> feat: add goldendict

- repos.yml
> feat: add modemmanager

- repos.yml
> feat: add valgrind-if-available

- repos.yml
dependency of `gst-plugins-bad1.0`
> feat: add shaderc

- repos.yml
dependency of `gst-plugins-bad1.0`
> feat: add openh264

- repos.yml
> feat: add libftdi

- repos.yml
dependency of `kfilemetadata-kf5`
> feat: add kdegraphics-mobipocket

- repos.yml
dependency of multiple `main` packages.
> feat: add clutter-1.0

- repos.yml
> feat: add ruby-pygments.rb

- repos.yml
format by https://gist.github.com/chenchongbiao/506fa354ab3f52ef0b8c212e18b222c7
Log: format repos.yml
> chore: format repos.yml

- repos.yml
> recreate ikiwiki & move to main

- repos.yml
> feat: add javascript-common

- repos.yml
dependency of various kde packages
> feat: add libkf5libkdepim

- repos.yml
dependency of `kfilemetadata-kf5`
> feat: add squashfuse

- repos.yml
> chore: add dwarves

- repos.yml
> chore: add cherrytree

- repos.yml
> chore: add cpputest

- repos.yml
> chore: add icecc

- repos.yml
> chore: add grsync

- repos.yml
> chore: update repos.yml

- repos.yml
Utilities for EROFS File System
玲珑构建依赖
Log: add reoi
> feat: add erofs-utils

- repos.yml
> chore: add 7zip

- repos.yml
```
libhfstospell11 >= 0.5.3 needed by libvoikko1
```
> feat: add hfst-ospell

- repos.yml
> chore: add rofi

- repos.yml
> chore: add playerctl

- repos.yml
> chore: add libmpdclient

- repos.yml
> chore: add hyprland

- repos.yml
> feat: add libmspack and clamtk and gnome-icon-theme

- repos.yml
> chore: add jerasure

- repos.yml
> chore: add chafa

- repos.yml
GNU R character string processing facilities
Log: add repo
> feat: add r-cran-stringi

- repos.yml
embeddable Javascript engine, development files
policykit-1 依赖
Log: add repo
> feat: add duktape

- repos.yml
Log: dependency of ibus-pinyin
> chore: add libpyzy

- repos.yml
multiple repository bootstrap based on apt
Log: add repo
> feat: add multistrap

- repos.yml
> add libsbsms

- repos.yml
dependencies of `golang-ginkgo` (upgraded version)
> feat: add golang-github-nxadm-tail and golang-gopkg-tomb.v1

- repos.yml
Displaying the graphical console of a virtual machine
Log: addrepo
> feat: add virt-viewer

- repos.yml
API to access the kernel tracefs directory (development files)
Log: add repo
> feat: add libtracefs, libtraceevent

- repos.yml
> chore: add pipx and it's dependencies

- repos.yml
Lightweight, robust, elegant syntax highlighting
Log: add repo
> feat: add node-prismjs

- repos.yml
Node.js module to copy to clipboard without flash
Log; add repo
> feat: add node-clipboard

- repos.yml
GWeather development files
Log: add repo
> feat: add libgweather4

- repos.yml
emulate chroot, bind mount and binfmt_misc for non-root users
Log: add repo
> feat: add proot

- repos.yml
ReportLab-based reStructuredText to PDF renderer
Log: add repo
> feat: add rst2pdf

- repos.yml
GCC cross compiler for ARM Cortex-R/M processors
Log: add repo
> fear: add gcc-arm-none-eabi

- repos.yml
> fear: add repo for docker.io

- repos.yml
> fix: fix repo.yml

- repos.yml
> feat: add repo for docker.io

- repos.yml
needed by deepin-desktop-environment-cli
> feat: add alsa-ucm-conf

- repos.yml
> chore: add reuse and it's dependencies

- repos.yml
dependency of upgraded `cryfs`
> feat: add range-v3

- repos.yml
dependency of `vcdimages` for `vlc`
> feat: add dpkg-awk

- repos.yml
> chore: remove rust-scopeguard

- repos.yml
> chore: add codeblocks

- repos.yml
flexible I/O tester
Log: add repo
> feat: add fio

- repos.yml
> chore: add fido2

- repos.yml
helper script to make the Debian source package
Log: add repo
> feat: add debmake

- repos.yml
> chore: add nghttp3

- repos.yml
> chore: Add gnome-panel

- repos.yml
u-boot menu update
Log: add repo
> feat: add u-boot-menu

- repos.yml
real-time audio streaming over the network
dependency of pipewire
> add roc-toolkit

- repos.yml
> feat: add u-boot for riscv

- repos.yml
> chore: add bpftrace

- repos.yml
> chore: add apps

- repos.yml
> chore: add clonezilla

- repos.yml
> feat: add libnbd

- repos.yml
> feat: add nbd

- repos.yml
> feat: add ipcalc

- repos.yml
> chore: add inxi

- repos.yml
> chore: add docker.io deps

- repos.yml
> chore: add cowsay

- repos.yml
> feat: add thrift

- repos.yml
> chore: add xmake

- repos.yml
> chore: add tbox

- repos.yml
> feat: add phpunit and php-codesniffer

- repos.yml
> chore: add mips cross build toolchain

- repos.yml
> feat: add repos for lolcat

- repos.yml
> feat: add repos for CasaOs

- repos.yml
> chore: add newlib

- repos.yml
> chore: add git-review

- repos.yml
> chore: add lintian deps

- repos.yml
> feat: add crash 

- repos.yml
> chore: add seafile

- repos.yml
> feat: add google-android-installers

- repos.yml
> chore: add dep of lintian

- repos.yml
> chore: add glmark2

- repos.yml
> chore: add fcitx5-table-extra

- repos.yml
> chore: add pyte

- repos.yml
> chore: add cabextract

- repos.yml
> chore: add nvtop

- repos.yml
> chore: add claws-mail

- repos.yml
> chore: add claws deps

- repos.yml
> chore: add xdg-terminal-exec

- repos.yml
> chore: add d-spy

- repos.yml
> chore: add kdiff3

- repos.yml
> chore: add osspd

- repos.yml
> chore: add netperf and iozone3

- repos.yml
> chore: add stress-ng

- repos.yml
> chore: add intel ipsec

- repos.yml
> chore: add gdb-doc

- repos.yml
Ref: https://github.com/rizinorg/cutter, https://github.com/eteran/edb-debugger
> feat: add reverse gui tools

- repos.yml
> feat: add cloc

- repos.yml
> chore: add deps for openjdk-17

- repos.yml
> chore: add kmscon

- repos.yml
> feat: add networkmanager-qt6

- repos.yml
> chore: add wget2&iotop-c

- repos.yml
* crun, lightweight OCI runtime
* wasmedge, development headers
Log: add repo
> chore: add repos for crun

- repos.yml
Add oceanbase into deepin repo
> feat: oceanbase

- repos.yml
> chore: add openjdk-17 dep

- repos.yml
> chore: add texstudio and deps

- repos.yml
> chore: add tomcat10

- repos.yml
> chore: add spring packages

- repos.yml
> chore: add prometheus-cpp

- repos.yml
> chore: add hustmirror-cli

- repos.yml
> chore: add docker-compose

- repos.yml
> chore: add uglifyjs

- repos.yml
> chore: add wmctrl

- repos.yml
> feat: Add liblatex-tounicode-perl and libbibtex-parser-per for suitesparse

- repos.yml
> chore: add bnd

- repos.yml
> chore: Add libmoose-autobox-perl

- repos.yml
> chore: add deps of rclone

- repos.yml
> chore: add deps for rclone (2)

- repos.yml
> chore: add deps for rclone (3)

- repos.yml
> chore: add deps for rclone (4)

- repos.yml
> chore: add deps for rclone (5)

- repos.yml
> chore: add go 1.21 1.22

- repos.yml
> chore: add refind

- repos.yml
> chore: add gdebi

- repos.yml
> chore: add sdl12-compat

- repos.yml
> chore: add global and xtrace

- repos.yml
> chore(repos.yml): add dependencies

- repos.yml
> feat: add gcc14 and llvm-18

- repos.yml
> chore: add icecc-monitor and bashdb

- repos.yml
> chore: Add intel openvino support

- repos.yml
> chore: add neovim's deps

- repos.yml
> chore: add libdecaf

- repos.yml
> chore: add slurp and grim

- repos.yml
> chore: add haskell repos

- repos.yml
> chore(repos.yml): add dacite

- repos.yml
结合 https://salsa.debian.org/haskell-team/DHG_packages 做haskell的批量更新与维护
> chore: Add ghc and haskell develop tools

- repos.yml
> chore: add box64

- repos.yml
> chore: add cockpit

- repos.yml
> chore: add tpm2-tools

- repos.yml
> chore: add kitty and deps

- repos.yml
> chore: add tcpdump

- repos.yml
> chore: add makedumpfile

- repos.yml
> chore: add yq direnv and tsocks

- repos.yml
> chore: add openjdk(18-21)

- repos.yml
> chore: add bolt

- repos.yml
> add xtensor

- repos.yml
> chore: remove useless openjdk-(18,19,20) add openjdk-8

- repos.yml
> chore: add openpace

- repos.yml
> chore: add misans and read-edid

- repos.yml
> chore: add log4cpp

- repos.yml
add qt6mpris
Log: add qt6mpris
> chore: add qt6mpris

- repos.yml
Reverts deepin-community/Repository-Manager#828
> Revert "add fonts-adobe-source-han-cjk"

- repos.yml
> fix: repo level

- repos.yml
> chore: add libmodule-manifest-perl

- repos.yml
Log: it needed by  python-distributed-doc
> chore: add  sass-stylesheets-bulma

- repos.yml
> chore: add binwalk

- repos.yml
> chore： yaml lint

- repos.yml
> chore: add blender

- repos.yml
> chore: add pystring

- repos.yml
> chore: add refpolicy

- repos.yml
> chore: add uresourced

- repos.yml
> feat: add open-gpu-kernel-modules

- repos.yml
> chore: add ptex-base

- repos.yml
> chore: add ncbi-blast+

- repos.yml
> add fcitx5-unikey

- repos.yml
> feat: add linyaps-box

- repos.yml
> chore: add ddccontroal and checksec

- repos.yml
> chore: add ddccontrol-db

- repos.yml
> chore: add qhttpengine

- repos.yml
> chore: add some R package

- repos.yml
> chore: add containers OCI stage1

- repos.yml
提供用于 Qt 6 各类 Model 的扩展辅助 Model 支持
> repo: kf6-itemmodels

- repos.yml
feat: Add aphinx-sitemap
Used for build packages as a dependency
Log: python, sphinx-sitemap, dependency
> feat: Add sphinx-sitemap

- repos-exit-records.yml
chore: Rm pkg-config package
Removed pkg-config package since it's now part of pkgconf
Log: pkg-config, pkgconf
> chore: Rm pkg-config package

- repos.yml
deepin-fcitx5-configtool dependency
> chore: add kf6-kwidgetsaddons/kitemviews

- repos.yml
step requires libqalculate-dev.
> chore: add libqalculate

- repos.yml
> add qtermwidget6

- repos.yml
> chore: add pcp

- repos.yml
> chore: add llvm-19 and spriv-19

- repos.yml
> chore: add deskflow and txt2tag

- repos.yml
needed by gnome-control-center
> Add gnome-bluetooth3

- repos.yml
> chore: add dump-init

- repos.yml
> chore: add vulkan-utility-libraries

- repos.yml
> chore: add xpadneo-dkms

- .github/workflows/auto-create-repo.yml
直接使用obs api创建项目,避免osc工具运行环境损坏导致的错误
> chore: Remove osc tools

- repos.yml
Add depends to support some python program
> add depends: python3-iniparse、crudini

- repos.yml
> feat： add nodejs deps

- repos.yml
1. binutils-xtensa
2. gcc-xtensa
3. libstdc++-arm-none-eabi
4. libstdc++-riscv64-unknown-elf
5. picolibc
> chore: add libstdc++ deps

- repos.yml
> chore: add llvm-20

- repos.yml
> chore: add zig0.14

- repos.yml
https://github.com/orgs/deepin-community/projects/492
https://build.deepin.com/project/show/deepin:CI:TestingIntegration:test-integration-pr-2654
> chore: add scilab deps

- repos.yml
https://github.com/orgs/deepin-community/projects/492
https://build.deepin.com/package/show/deepin:CI:TestingIntegration:test-integration-pr-2654/lucene8
> chore: add lucene8 deps

- repos.yml
https://build.deepin.com/project/show/deepin:CI:TestingIntegration:test-integration-pr-2654
> chore: add janest-base ocaml-intrinsics-kernel ppx-here ppx-let

- repos.yml
> feat: add asmc

- repos.yml
> feat: add openrazer

- repos.yml
> feat: add sparse

- repos.yml
> feat: add rsetup

- repos.yml
> feat: add librtui

- repos.yml
> chore: add picocom

- repos.yml
> feat: add waydroid

- repos.yml
> feat: add rime-wanxiang

- repos.yml
**can-utils 简介与使用指南**
**1. 概述**  
`can-utils` 是 Linux 下用于 **CAN（Controller Area Network）总线**开发和测试的工具集合，基于内核的 SocketCAN 子系统实现。适用于汽车电子、工业控制及嵌入式系统开发。
---
**2. 核心工具**  
- **cansend**：发送单帧 CAN 数据。  
```bash
cansend can0 123#AABBCCDD
```
- **candump**：实时捕获并显示 CAN 数据。  
```bash
candump can0
```
- **canplayer**：回放记录的 CAN 日志（如 `.log` 文件）。  
```bash
canplayer -I recorded.log
```
- **cangen**：生成随机或周期性 CAN 数据，用于压力测试。  
- **canlogserver**：将 CAN 数据流式传输至网络，支持多客户端监听。
---
**3. 安装方法**  
- **Debian/Ubuntu**：  
```bash
sudo apt install can-utils
```
- **源码编译**：  
```bash
git clone https://github.com/linux-can/can-utils
cd can-utils && make
```
**依赖项**：确保内核支持 SocketCAN，加载模块：  
```bash
sudo modprobe can && sudo modprobe vcan  # 虚拟 CAN 接口
```
---
**4. 使用示例**  
- **设置虚拟 CAN 接口**（测试用）：  
```bash
sudo ip link add …
```
> chore: add can-utils

- repos.yml
提供一个开源版本的安装器，基于 calamares 安装框架使用
> feat: add kpmcore calamares

- repos.yml
基于 calamares 安装框架，添加 deepin 设置和主题
> feat: Add calamares-settings-deepin

- repos.yml
necessary for fix https://bbs.deepin.org/post/286305
> feat: add pyopengl and its dependencies

- repos.yml
So that we can enjoy the starry sky on Deepin
> feat: add stellarium and its dependencies

- repos.yml
https://bbs.deepin.org/post/286729
> chore: add zlog

- repos.yml
https://bbs.deepin.org/post/286955
> feat: add mosquitto and deps

- repos.yml
packet crafting and sniffing library - development files
Log: add repo
> feat: Add  libtins

- repos.yml
dtk2widget
dtk2core
spark-store
> Add: dtk2widget dtk2core  spark-store

- repos.yml
> feat： add lxqt deps

- repos.yml
https://bbs.deepin.org/post/288037
> feat: add ardourt and its dependencies

- repos.yml
- fsverity-utils
- rust-rpm-sequoia
- utf8-locale
> add rpm's dependencies

- repos.yml
- rust-cdylib-link-lines
- rust-sequoia-openpgp
- rust-sequoia-policy-config
- rust-ed25519
- rust-curve25519-dalek
---
注意：rust-ed25519 和 rust-curve25519-dalek 的产物都是源码 all 包，他俩互相依赖
> add rust-rpm-sequoia's dependencies

- repos.yml
https://github.com/deepin-community/wcwidth/pull/1 needs it
> add requests-file

- repos.yml
SANE backend for AirScan (eSCL) and WSD document scanner
> feat: add sane-airscan

- repos.yml
https://launchpad.net/~xuzhen666/+archive/ubuntu/ppsspp/+packages
> feat: add ppsspp

- repos.yml
打包来自ubuntu
https://mirrors.aliyun.com/ubuntu/pool/main/d/dotnet8/
> feat: add dotnet8
