deepin-community/Repository-Manager

- repos.yml
an expressive monospaced font family that’s built with clarity, legibility, and the needs of developers in mind.
Log: add fonts-intel-one-mono
Issue: [https://github.com/deepin-community/sig-deepin-sysdev-team/issues/55](url)
Task: [https://github.com/deepin-community/sig-deepin-sysdev-team/issues/4](url)
Influence: fonts intel-one-mono would be added
> feat: add fonts-intel-one-mono

- repos.yml
Log: This metapackage enables feature "serde" for the Rust either crate, by pulling in any additional dependencies needed by that feature.
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/64
Tast: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/5
Influence: rust-either would be added
> feat: add rust-either

- repos.yml
Rust crate for FFI bindings to all of Windows API.
Log: add rust-winapi-i686-pc-windows-gnu
Issue: deepin-community/sig-deepin-sysdev-team#36
> feat: add rust-winapi-i686-pc-windows-gnu

- repos.yml
Defines the macros defer!, defer_on_unwind!, defer_on_success! as shorthands for guards with one of the implemented strategies.
Log: add rust-scopeguard
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/70
> feat: add rust-scopeguard

- repos.yml
This package contains the source for the Rust log crate, packaged by debcargo for use with cargo and dh-cargo.
Log: add rust-log
Issue: [https://github.com/deepin-community/sig-deepin-sysdev-team/issues/55](https://github.com/deepin-community/Repository-Manager/pull/url)
> feat: add rust-log

- repos.yml
Rust target for the Windows operating system, used for building Rust applications that run on 64-bit Windows systems using the GNU toolchain.
Log: add rust-winapi-x86-64-pc-windows-gnu
Issue: deepin-community/sig-deepin-sysdev-team#37
> feat: add rust-winapi-x86-64-pc-windows-gnu

- repos.yml
rust-clap, Rust Command Line Argument Parser.
rust-clap-lex, Minimal, flexible command line parser.
rust-termcolor, Simple cross platform library for writing colored text to a terminal.
rust-os-str-bytes, Utilities for converting between byte sequences and platform-native st>
rust-winapi-util, Dumping ground for high level safe wrappers over winapi.
Log: rust-clap, rust-clap-lex, rust-termcolor, rust-os-str-bytes, rust-winapi-util would >
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/76
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/83
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/82
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/84
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/28
> feat: add rust-clap, rust-clap-lex, rust-termcolor, rust-os-str-bytes

- repos.yml
This program converts HTML directly to PostScript. The HTML code can be retrieved from one or more URLs or local files, specified as parameters on the command line.
Log: add html2ps
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/73
> feat: add html2ps

- repos.yml
This package contains the source for the Rust cexpr crate.
Log: add rust-cexpr
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/75
> feat: add rust-cexpr, rust-lexical-core

- repos.yml
bpython, fancy interface to the Python 3 interpreter butt, an easy to use, multi OS streaming tool.
Log: add bpython, butt
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/87
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/88
> feat: add bpython, butt

- repos.yml
Rust crate that provides bindings for libclang, the C interface to the Clang compiler.
Log: add rust-clang-sys
Issue: deepin-community/sig-deepin-sysdev-team#90
> feat: add rust-clang-sys

- repos.yml
fonts-google-noto-sans-simplified-chinese, Noto Sans SC is an unmodulated (“sans serif”) design for languages in mainland China that use the Simplified Chinese variant of the Han ideograms.
iotop, simple top-like I/O monitor
exim4, metapackage to ease Exim MTA (v4) installation
Log: add fonts-google-noto-sans-simplified-chinese,iotop,exim4
Issue:
deepin-community/sig-deepin-sysdev-team#85
deepin-community/sig-deepin-sysdev-team#86
deepin-community/sig-deepin-sysdev-team#89
> feat: add fonts-google-noto-sans-simplified-chinese,iotop,exim4

- repos.yml
Firacode is a free monospaced font with programming ligatures
Log: add firacode
Issue: deepin-community/sig-deepin-sysdev-team#43
> feat: add firacode

- repos.yml
fail2ban: ban hosts that cause multiple authentication errors
xburn: CD-burner application for Xfce Desktop Environment
tix: library for Tk -- development package
iftop: displays bandwidth usage information on an network interface
ristretto: lightweight picture-viewer for the Xfce desktop environment
Log: add fail2ban, xfburn, tix, iftop, ristretto
Issue:
deepin-community/sig-deepin-sysdev-team#97
deepin-community/sig-deepin-sysdev-team#100
deepin-community/sig-deepin-sysdev-team#102
deepin-community/sig-deepin-sysdev-team#104
deepin-community/sig-deepin-sysdev-team#110
> feat: add fail2ban, xfburn, tix, iftop, ristretto

- repos.yml
This package provides a PEM file reader for Network Security Services (NSS), implemented as a PKCS#11 module.
Log: add nss-pem
Issues: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/156
> feat: add nss-pem

- repos.yml
golang-github-openprinting-goipp is an IPP core protocol in pure Go Library (RFC 8010). python-tokenize-rt is a wrapper around the Python stdlib `tokenize` which roundtrips.
Log: add golang-github-openprinting-goipp, python-tokenize-rt Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/103 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/130
> feat: add golang-github-openprinting-goipp, python-tokenize-rt

- repos.yml
It peeking_take_while peeks at the next item in the iterator and runs the predicate on that peeked item.
Log: add rust-peeking-take-while
Issue:deepin-community/sig-deepin-sysdev-team#96
> feat: add rust-peeking-take-while

- repos.yml
Rust-thread-local contains the source for the Rust thread_local crate, packaged by debcargo for use with cargo and dh-cargo.
Acpi shows the information of the ACPI device.
Raleway is an elegant sans-serif typeface family.
Log: add rust-thread-local, acpi, fonts-raleway
Issue: deepin-community/sig-deepin-sysdev-team#138, deepin-community/sig-deepin-sysdev-team#167, deepin-community/sig-deepin-sysdev-team#168
> feat: add rust-thread-local, acpi, fonts-raleway

- repos.yml
TOIlet prints text using large characters made of smaller characters. 
Larch is a tool to copy messages from one IMAP server to another quickly and safely. 
The swtpm package provides TPM emulators that listen for TPM commands on sockets, character devices, or CUSE devices. 
NYACC is set of guile modules for generating parsers and lexical analyzers. 
Friso is an open source high performance Chinese word splitter.
Log: add toilet, larch, swtpm, nyacc, friso
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/112 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/129 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/125 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/151 …
> feat: add toilet, larch, swtpm, nyacc, friso

- repos.yml
rust-serde, a framework for serializing and deserializing Rust data structures efficiently and generically. rust-arbitrary, the Arbitrary crate lets you construct arbitrary instances of a type. Log: add rust-serde, rust-arbitrary
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/164 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/165
> feat: add rust-serde, rust-arbitrary

- repos.yml
hexchat: IRC client for X based on X-Chat 2: HexChat is a graphical IRC client with a GTK+ GUI. 
xcvt: library for SSA/ASS subtitles rendering.
xserver-xorg: Xorg X server - core server: This package is built from the X.org xserver module. 
libss: Command line interface Parsing library.
log: add hexchat, xcvt, xserver-xorg, libss
issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/169 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/181 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/183 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/189
> feat: add hexchat, xcvt, xserver-xorg, libss

- repos.yml
Compiler intrinsics used by the Rust compiler
Explicitly empty crate for rust-lang/rust integration
Log: add rust-compiler-builtins, rust-rustc-std-workspace-core
Issue: deepin-community/sig-deepin-sysdev-team#111,deepin-community/sig-deepin-sysdev-team#113
> feat: add rust-compiler-builtins, rust-rustc-std-workspace-core

- repos.yml
This package contains the source for the Rust atty crate
Log: add rust-atty
Issue: deepin-community/sig-deepin-sysdev-team#38
> feat: add rust-atty

- repos.yml
The isochron program is a real-time application for testing Time Sensitive Networking equipment. 
KTX (Kombat Teams eXtreme) is a popular QuakeWorld server modification, adding numerous features to the core features of the server. 
mctc-lib is a modular computation tool chain library (development files) 
distance is a Python library for comparing sequences 
Libtpms is a library that provides TPM functionality. Libtpm is used by swtpm package.
Log: add isochron, ktx, mctc-lib, distance, libtpms 
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/160 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/161 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/190 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/191 …
> feat: add isochron, ktx, mctc-lib, distance, libtpms

- repos.yml
SIP API for Java
Base libraries used by software from the SIS division at ETH Zurich 
easy-to-use HDF library for Java
web-page layout and decoration framework
Log: add java-sip-api, libsis-base-java, libsis-jhdf5-java, sitemesh
Issue: deepin-community/sig-deepin-sysdev-team#195,deepin-community/sig-deepin-sysdev-team#196,deepin-community/sig-deepin-sysdev-team#197,deepin-community/sig-deepin-sysdev-team#198
> feat: add java-sip-api, libsis-base-java, libsis-jhdf5-java, sitemesh

- repos.yml
Fonts-linex provides fonts suitable for education and institutional use. 
Fonts-ecolier-court provides a cursive font covering the basic latin range with a ink and dip pen style. 
Fonts-femkeklaver is a simple handwriting font with strong repeated tracing. 
Fonts-mplus is a collection of sans serif fonts with different weights, including Japanese glyphs.
Log: add fonts-linex, fonts-ecolier-court, fonts-femkeklaver, fonts-mplus
Issue: deepin-community/sig-deepin-sysdev-team#216, deepin-community/sig-deepin-sysdev-team#218, deepin-community/sig-deepin-sysdev-team#219, deepin-community/sig-deepin-sysdev-team#220
> feat: add fonts-linex, fonts-ecolier-court, fonts-femkeklaver, fonts-mplus

- repos.yml
FORT validator performs the validation of the RPKI repository and serves the ROAs to the routers. 
libite holds useful functions and macros developed by both Finit and the OpenBSD project. 
libuEv is a small event loop that wraps the Linux epoll() family of APIs. 
Kconfiglib is a Kconfig implementation in Python.
Log: add fort-validator, libite, libuev, kconfiglib 
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/209 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/210 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/211 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/222
> feat: add fort-validator, libite, libuev, kconfiglib

- repos.yml
Paperwork is a personal document manager.
Library to access scanner
ISO databases accessible from Python 3
Python wrapper for OCR engines (Python 3)
Python 3 bindings for libpillowfight
Log: add paperwork,libinsane,pycountry,python-pyocr,libpillowfight
Issue: deepin-community/sig-deepin-sysdev-team#231,deepin-community/sig-deepin-sysdev-team#232,deepin-community/sig-deepin-sysdev-team#233,deepin-community/sig-deepin-sysdev-team#234,deepin-community/sig-deepin-sysdev-team#235
> feat: add paperwork,libinsane,pycountry,python-pyocr,libpillowfight

- repos.yml
It is a command-line tool which extracts the text out of OpenDocument Texts, as produced by OpenOffice.org, KOffice, StarOffice and others.
Log: add odt2txt
Issue:deepin-community/sig-deepin-sysdev-team#239
> feat: add odt2txt

- repos.yml
This package contains the source for the Rust syn crate This package contains the source for the Rust derive_arbitrary crate This package contains the source for the Rust smallvec crate
Log: add rust-syn-1, rust-derive-arbitrary, rust-smallvec
Issue: deepin-community/sig-deepin-sysdev-team#214, deepin-community/sig-deepin-sysdev-team#215, deepin-community/sig-deepin-sysdev-team#221
> feat: add rust-syn-1, rust-derive-arbitrary, rust-smallvec

- repos.yml
rust-humantime, Parser and formatter for std::time::{Duration, SystemTime} 
rust-device-tree, Reads and parses Linux device tree images Log: add rust-humantime, rust-device-tree
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/32 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/255
> feat: add rust-humantime, rust-device-tree

- repos.yml
mate-submodules: MATE code components provided as Git submodule repository
gla11y:  Automatic check of accessibility of .ui files
pluma: official text editor of the MATE desktop environment
Log: add mate-submodules, gla11y, pluma
Issue:
deepin-community/sig-deepin-sysdev-team#257
deepin-community/sig-deepin-sysdev-team#258
deepin-community/sig-deepin-sysdev-team#259
> feat: add mate-submodules, gla11y, pluma

- repos.yml
OpenSubdiv is a set of open source libraries that implement high performance subdivision surface (subdiv) evaluation on massively parallel CPU and GPU architectures. 
The spacenav project provides a free, compatible alternative to the proprietary 3Dconnexion SDK for their 3D input devices. 
log4cplus is a simple to use C++ logging API providing thread-safe, flexible, and arbitrarily granular control over log management and configuration. 
Imath is a basic, light-weight, and efficient C++ representation of 2D and 3D vectors and matrices and other simple but usefulmathematical objects, functions, and data types common in computer graphics applications, including the “half” 16-bit floating-point type.
Log: add opensubdiv, libspnav, log4cplus, imath
Issue: …
> feat: add opensubdiv, libspnav, log4cplus, imath

- repos.yml
Add `bird`, `bird2`, `babeld`, `base16384`, `btop`
---
`bird`: BIRD Internet Routing Daemon, version 1.x
`bird2`: BIRD Internet Routing Daemon, version 2.x
`babeld`: Routing daemon using babel protocol
`base16384`: Encode binary files to printable utf16be
`btop`: Modern and colorful command line resource monitor that shows usage and stats
> feat: add bird, bird2, babeld, base16384, btop

- repos.yml
Attribute macro to require a function can't ever panic.
Log: rust-no-panic would be added.
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/144
> feat: add rust-no-panic

- repos.yml
The spacenav project provides a free, compatible alternative to the proprietary 3Dconnexion SDK for their 3D input devices 
log4cplus is a simple to use C++ logging API providing thread-safe, flexible, and arbitrarily granular control over log management and configuration. 
Imath is a basic, light-weight, and efficient C++ representation of 2D and 3D vectors and matrices and other simple but usefulmathematical objects, functions, and data types common in computer graphics applications, including the “half” 16-bit floating-point type.
Log: add libspnav, log4cplus, imath
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/245 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/256 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/263
> feat: add libspnav, log4cplus, imath

- repos.yml
ipp-usb is a userland driver for USB devices supporting the IPP over USB protocol. 
evilwm is based on aewm by Decklin Foster.
python-arrow is a Python3 library to manipulate dates, times, and timestamps.
python-exif is a Python library to extract Exif information from digital camera image files. 
pefile is a Python module to read and work with Portable Executable (PE) files.
Log: add ipp-usb, evilwm, python-arrow, python-exif, python-pefile 
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/287 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/293 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/256 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/298 
https://github.com/deepin-community/sig-deepin-sysdev-team/iss …
> feat: add ipp-usb, evilwm, python-arrow, python-exif, python-pefile

- repos.yml
rust-hashbrown,rust port of Google's SwissTable hash map.
rust-once-cell,attribute macro to require a function can't ever panic.
Log: rust-hashbrown and rust-once-cell would be added.
Issue: 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/109
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/145
> feat: add rust-hashbrown and rust-once-cell

- repos.yml
This library provides routines for packing and unpacking nv pairs for transporting data across process boundaries
Log: add zfs-linux
Issue: deepin-community/sig-deepin-sysdev-team#314
> feat: add zfs-linux

- repos.yml
This is an interface to the GNU Compiler Collection for the collection and analysis of compiler-generated binaries.
Log: add libabigail
Issue: deepin-community/sig-deepin-sysdev-team#315
> feat: add libabigail

- repos.yml
The termcolor Python module provides ANSII Color formatting for output in terminal. 
Geographiclib is a C++ library to solve some geodesic problems 
python-prov is a library for W3C Provenance Data Model supporting PROV-JSON and PROV-XML import/export. 
python-geojson contains Python 3 bindings and utilities for GeoJSON 
gmpy provides interfaces GMP to Python 3 for fast, unbound-precision computations
Log: add python-termcolor, geographiclib, python-prov, python-geojson, python-gmpy2 
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/305 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/327 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/328 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/330 …
> feat: add python-termcolor, geographiclib, python-prov, python-geojson, python-gmpy2

- repos.yml
Custom icon webfonts from the comfort of the command line
Thai DejaVu-compatible fonts
Meta package to install all Malayalam fonts
Truetype fonts for Cyrillic-based Uralic languages
"AR PL UKai" Chinese Unicode TrueType font collection Kaiti style
Fork of the iconic font and CSS toolkit
Material Design Icons DX
Log: add fonts-arundina,fonts-mlym,fonts-uralic,fonts-arphic-ukai,fonts-material-design-icons-iconfont 
Issues:deepin-community/sig-deepin-sysdev-team#266 
Issues:deepin-community/sig-deepin-sysdev-team#267 
Issues:deepin-community/sig-deepin-sysdev-team#268 
Issues:deepin-community/sig-deepin-sysdev-team#269 
Issues:deepin-community/sig-deepin-sysdev-team#271
> feat: add fonts-arundina,fonts-mlym,fonts-uralic,fonts-arphic-ukai,fonts-material-design-icons-iconfont

- repos.yml
arping, sends IP and/or ARP pings (to the MAC address)
speedtest-cli, Command line interface for testing internet bandwidth using speedtest.net
plocate, much faster locate
plzip, parallel, lossless data compressor based on the LZMA algorithm
ncftp, User-friendly and well-featured FTP client
memtester, Utility for testing the memory subsystem
arp-scan, arp scanning and fingerprinting tool
Log: add arping,speedtest-cli,plocate,plzip,ncftp,memtester,arp-scan
Issue: 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/289
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/290
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/292
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/294 …
> feat: add arping,speedtest-cli,plocate,plzip,ncftp,memtester,arp-scan

- repos.yml
kde-dev-utils: This package builds kpartloader and kuiviewer.
The source code repositories corresponding to xcvt, xserver xorg core, libss(2) and jq already exist, which are: libxcvt, xorg-server, e2fsprogs and jq.
log: add kde-dev-utils and delete xcvt, xserver-xorg-core, libss, jq
issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/349
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/238
> feat: add kde-dev-utils and delete xcvt, xserver-xorg-core, libss, jq

- repos.yml
In `auto-create-repo.yml`:
```
reponame = os.popen("cat diff | (grep '+  - repo:'||true) |awk '{print $4 $5}' ").read()
delrepos = os.popen("cat diff | (grep '\-  - repo:'||true) |awk '{print $4 $5}' ").read()
```
> fix: add indentation for repos.yml

- repos.yml
Go programming language compiler - metapackage
Log: add golang-1.15 to fix snapd
Issues: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/381
> feat: add golang-1.15 to fix snapd

- repos.yml
jpeginfo can be used to generate informative listings of jpeg files.
Log: add jpeginfo
Issue: deepin-community/sig-deepin-sysdev-team#388
> feat: add jpeginfo

- repos.yml
Braa is a mass snmp scanner.
Fonts-cabinsketch is a playful sister of the Cabin font family.
Pgpgpg is a wrapper around GNU Privacy Guard which takes PGP 2.6 command line options, translate them and then call GnuPG to perform the desired action.
Ripit is a textbased audio CD ripper.
Blop is bandlimited wavetable-based oscillator plugins for LADSPA hosts.
Ddate convert Gregorian dates to Discordian dates.
Netmask helps determine network masks.
Colortest utilities to test color capabilities of terminal.
Log: add braa, fonts-cabinsketch, pgpgpg, ripit, blop, ddate, netmask. colortest
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/329, https://github.com/deepin-community/sig-deepin-sysdev-team/issues/331, https://github.com/deepin-community/sig-deepin-sysdev-team/issu …
> feat: add braa, fonts-cabinsketch, pgpgpg, ripit, blop, ddate, netmask, colortest

- repos.yml
Fast, light and extensible chat client (metapackage) .
遵循 LGPL 的加密库 - 运行库.
GNU TLS library - main runtime library.
Log: add weechat,libgcrypt20,gnutls28
Issue: deepin-community/sig-deepin-sysdev-team#361,deepin-community/sig-deepin-sysdev-team#362,deepin-community/sig-deepin-sysdev-team#363
> feat: add weechat,libgcrypt20,gnutls28

- repos.yml
agave is a fixed-width outline typeface, designed and produced by type agaric.
Lemonada is a modern Arabic and Latin typeface family.
Jura Font Project by Daniel Johnson.
log: add fonts-agave, fonts-lemonada, fonts-jura
issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/386
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/392
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/391
> feat: add fonts-agave, fonts-lemonada, fonts-jura

- repos.yml
rdesktop is an open source client for Windows NT/2000 Terminal Server and Windows Server 2003/2008.
Log: add rdesktop
Issue: deepin-community/sig-deepin-sysdev-team#395
> feat: add rdesktop

- repos.yml
Add package: 
```
golang-github-pelletier-go-buffruneio
golang-github-akamensky-argparse
golang-github-fatih-color
golang-github-google-gopacket
golang-github-gorilla-websocket
golang-github-oschwald-maxminddb-golang
golang-github-rodaine-table
golang-github-spf13-viper
golang-github-tidwall-gjson
```
Required by `nexttrace`
> feat: add dependencies for nexttrace

- repos.yml
python-editor is a library that provides the editor module for programmatically interfacing with your system's $EDITOR. CSS parser provides utilities for parsing, serialising CSS in Python. 
python-configargparse is replacement for argparse with config files and environment variables. 
python-iniparse could access and modify configuration data in INI files (Python 3) 
python-utmp provides 3 modules to access utmp and wtmp records.
Log: add python-editor, python-css-parser, python-configargparse, python-iniparse, python-utmp 
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/416 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/419 
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/421 …
> feat: add python-editor, python-css-parser, python-configargparse, python-iniparse, python-utmp

- repos.yml
bsdmainutils: Transitional package for more utilities from FreeBSD.
exfatprogs: Tools to manage extended file allocation table filesystem. This package provides tools to create, check, dump and label the filesystem.
ntpsec: Network Time Protocol daemon/utilities (transitional package).
tcpdump: command-line network traffic analyzer.
log: add bsdmainutils, exfatprogs, ntpsec, tcpdump 
issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/448 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/417 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/433 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/444
> feat: add bsdmainutils, exfatprogs, ntpsec, tcpdump

- repos.yml
libgssglue provides a gssapi interface, but does not implement any gssapi mechanisms itself
Log: add libgssglue
Issue: deepin-community/sig-deepin-sysdev-team#398
> feat: add libgssglue

- repos.yml
Package `golang-github-google-gopacket` actually comes from `gopacket`.
> fix: change repo name, format yaml file

- .github/workflows/auto-create-repo.yml
Failed in workflow `init osc`
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/d/debootstrap/debootstrap_1.0.126%2bnmu1ubuntu0.4_all.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```
> fix: add apt update in workflow

- repos.yml
ssh-tools, collection of various tools using ssh
sxhkd, Simple X hotkey daemon
sm, Displays a short text fullscreen
fscrypt, Tool for managing Linux filesystem encryption
empire, war game of the century
pngcheck, print info and check PNG, JNG and MNG files
sakura, simple but powerful libvte-based terminal emulator
Log: add ssh-tools,sxhkd,sm,fscrypt,empire,pngcheck,sakura
Issue:
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/399
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/400
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/402
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/405
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/414
https://github.com/deepin-community/sig-deepin-sysdev-team/issues/41 …
> feat: add ssh-tools,sxhkd,sm,fscrypt,empire,pngcheck,sakura

- repos.yml
* jpeg-xl is needed by kimageformats, which is an important package of kde.
log: add jpeg-xl
> feat: add a new repo

- repos.yml
`arch-test`: detect architectures supported by your machine/kernel
Needed by `mmdebstrap` when creating for foreign arch
> feat: add package arch-test

- repos-exit-records.yml
ldb相关组件已全部转移至samba中，现由samba提供相关软件包
https://github.com/deepin-community/samba/pull/2
> feat: remove ldb

- repos-exit-records.yml
ppx-tools-versioned is an old library that do no longer compile with. current OCaml version https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006355
Log: delete package
> chore: delete ppx-tools-versioned

- repos.yml
VAAPI driver for the Intel GEN8+ Graphics family
Log: add repo
> feat: add repo

- repos.yml
printer backend for Canon BJNP protocol
Log: add repo
> chore: add cups-backend-bjnp

- repos.yml
build-time test dependency of krb5
> feat: add pyrad and python-kdcproxy

- repos.yml
`nothing provides python3-werkzeug >= 2.0 needed by python3-flask` when building `curl`
> feat: add python-werkzeug

- repos.yml
dependency of `python-werkzeug`
> feat: add python-ephemeral-port-reserve

- repos.yml
Align and Zip type-classes from the common Semialign ancestor
Log: add repo
> feat: add haskell-semialign

- repos.yml
Allow aeson data types to be used with Lua
Log: add repo
> feat: add haskell-hslua-aeson

- repos.yml
GitHub CLI, GitHub’s official command line tool
Log: add repo
> feat: add gh

- repos.yml
`libftdi1` and `libftdi` are different packages.
dependency of `pulseaudio`
> feat: add libftdi1

- repos.yml
`golang-goprotobuf-dev` is now provided by `golang-github-golang-protobuf-1-3`
> feat: add golang-github-golang-protobuf-1-3

- repos.yml
> feat: add lsb-release-minimal

- .github/workflows/auto-create-repo.yml
> fix(CI): repos.yml排序导致的obs仓库删除

- repos.yml
Log: wlroots12 is stable, so we don't need wlroots-git anymore
> chore: remove wlroots-git

- repos-exit-records.yml
> Remove: remove llvm 12,13,14

- repos.yml
deepin Linux Kernel Runtime Guard, fork from https://github.com/lkrg-org/lkrg
> feat: add deepin-lkrg

- .github/workflows/auto-create-repo.yml
新版本require存在问题,需要等https://github.com/octokit/octokit.js/pull/2665 合并才能正常
> fix(CI): use old octokit version to support require

- repos.yml
for jupyter-notebook build depends
> chore: Add libjs-codemirror and libjs-jquery-typeahead

- repos.yml
为glyphslib依赖，同时为预装的fonts-cantarell的间接构建依赖，因此需要放到main里面
> chore: Add python-openstep-plist

- repos.yml
These packages are dependencies for updated QScintilla2.
> chore(repos.yml): add pyqt6, pyqt6-sip

- repos.yml
avoid name conflict with deepin-community/repo
> fix: rename repo to repo-tool

- repos.yml
https://github.com/errorcode7/zig (added debian already)
note: build zig ,need llvm18 ,ref:  https://errorcode7.github.io/linux/build_zig.html
> feat: add zig language

- repos.yml
bpython requires python-curtsies and python-cwcwidth, and python-curtsies requires python-blessed.
> chore: add python-blessed python-curtsies python-cwcwidth
